server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://${BOOKDB_HOST:localhost}:${BOOKDB_PORT:5432}/${BOOKDB_NAME:bookservicedb}
    username: ${BOOKDB_POSTGRES_USER:postgres}
    password: ${BOOKDB_POSTGRES_PASSWORD:1234}
  liquibase:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true

openapi:
  service:
    title: API Book-service
    version: 1.0.0
    url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080} #api gateway url

springdoc:
  api-docs:
    path: /book-app/v3/api-docs
  swagger-ui:
    path: /book-app/swagger-ui.html
