server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://${ORDERBD_HOST:localhost}:${ORDERDB_PORT:3306}/${ORDERDB_NAME:orderdb}
    username: ${ORDERDB_USERNAME:superroot}
    password: ${ORDERDB_PASSWORD:password}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true

openapi:
  service:
    title: API Order-service
    version: 1.0.0
    url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080} #api gateway url

springdoc:
  api-docs:
    path: /order-app/v3/api-docs
  swagger-ui:
    path: /order-app/swagger-ui.html
