server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${CARTDB_HOST:localhost}:${CARTDB_PORT:3306}/${CARTDB_NAME:shopping-cartdb}
    username: ${CARTDB_USERNAME:superroot}
    password: ${CARTDB_PASSWORD:password}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true

openapi:
  service:
    title: shoppingCart-service doc
    version: 1.0.0
    url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080} #api gateway url

springdoc:
  api-docs:
    path: /shopping-cart-app/v3/api-docs
  swagger-ui:
    path: /shopping-cart-app/swagger-ui.html
