server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${USERDB_HOST:localhost}:${USERDB_PORT:3306}/${USERDB_NAME:userdb}
    username: ${USERDB_USERNAME:superroot}
    password: ${USERDB_PASSWORD:password}
  flyway:
    enable: true
    locations: classpath:db/migration/structure, classpath:db/migration/data
    validation-on-migrate: true
    default-schema: ${USERDB_NAME:userdb}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret:  ${JWT_SECRET:foottakemeetexampleproopervendor}
  expiration: ${JWT_EXPIRATION:3000000}

openapi:
  service:
    title: API User-service
    version: 1.0.0
    url: http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8080} #api gateway url

springdoc:
  api-docs:
    path: /user-app/v3/api-docs
  swagger-ui:
    path: /user-app/swagger-ui.html
